### ISSUE TITLE
Improvements to L0 compaction

### ISSUE THREAD

**Issue by purplefox** [spirit-labs/tektite#10]
L0 compaction is currently the main bottleneck to throughput.

This is because different nodes register tables into L0 with widely overlapping key ranges. So L0 tables are likely to overlap with each other, and they're likely to overlap with most of L1 too, so an L0 compaction typically involves most of L0 and L1. This is processed on a single worker, and while compaction is occurring and L0 has reached max size no more tables can be registered with L0. This can push back to the nodes, and when the store memtable queue is full it pushes back to writes and processing can be blocked.

In order to speed up L0 compaction we need to make it parallelisable, i.e. somehow split up the compaction into multiple non overlapping compactions that can proceed in parallel, and be executed on different workers.

One solution to this is as follows:

The basic idea is to ensure that each processor only ever pushes sstables containing keys in ranges that don't overlap with other processors, so we know that tables in L0 from different processors don't overlap and can therefore be compacted to L1 in parallel.

Currently the key prefix for each entry in the database is `[slab_id, partition_id]`, where the slab is a stream or table. It's not possible to assign contiguous ranges of prefixes like this across multiple processors, which is what we would have to do to get the non overlapping characteristics we want without recalculating the entire association for prefix -> processor every time a new table/stream was created/deleted. This is not really feasible.

However, we could change the prefix to `[partition_hash, slab_id]`. Here, `partition_hash` is a sha-1 hash of the `[mapping_id, partition_id]` (don't worry too much about mapping id here), and first 128 bits taken, so like a UUID. Using a sha hash gives very even distribution. 

To find the processor for the partition hash, think of the hash as a number from 0 to (2^128) -1, and we just divide that range across all processors. processor 0 gets the first slice, then processor 1 gets the next slice etc.

This means that each processor will only process keys which like in a range that does not overlap with other processors.

We then change the store push, so we push a different sstable for each processor, and that means that all sstables arriving in L0 from different processors won't have any key overlap so L0->L1 compaction can be parallelised and we can scale write throughput theoretically linearly as we add more processors.

The downside of this is that it makes knowing when a table deletion is complete more difficult. Currently to know if a table deletion is complete, we just execute a level manager request to return names of all tables in the range of the slab id, as this is the first element in the key. But with the new prefix structure the slab id is not the first element in the key so it makes knowing when there are no more keys for the table left in the database more difficult, without searching for every partition of the deleted table.

**Comment by naveen246** [comment]
When compaction has started on L0 (and assuming all data from L0 will be pushed to L1 after compaction), can we treat currentSize of L0 to be 0(zero) and start registering new tables with L0 (while L0 compaction is going on)?

**Comment by purplefox** [comment]
> When compaction has started on L0 (and assuming all data from L0 will be pushed to L1 after compaction), can we treat currentSize of L0 to be 0(zero) and start registering new tables with L0 (while L0 compaction is going on)?

Compaction doesn't prevent new tables being registered
