### ISSUE TITLE
Feature: Add aggregation functions

### ISSUE THREAD

**Issue by adpande** [spirit-labs/tektite#118]
Hi @purplefox  very excited about this new project!!

I request to also add the following functions to the Aggregation or Functions

- diff - difference between first and the last value - to calculate daily power consumption for an IoT Electricity meter.
- range
- stddev
- variance
- percentile
- median
- first - will return first record of time window
- last - will return last record of time window

Thanks & Regards,
Abhishek

**Comment by purplefox** [comment]
Hi @adpande - would be great to have these functions.

One thing to think about - would the storage overhead for some of these functions be large? I'm thinking that some of them will need to retain all values in the window until the window closes in order to compute the aggregate?

**Comment by adpande** [comment]
for come can be large then we can omit them for now. but diff, range, first, last  should be enough to start with. I think these functions can be for non window aggregators as well.

**Comment by purplefox** [comment]
Sounds good, go for it!

**Comment by purplefox** [comment]
Hey @adpande - just wondering how this is going?
