### ISSUE TITLE
Typos in Documentation

### ISSUE THREAD

**Issue by vchandela** [spirit-labs/tektite#159]
1. `int` -> Converts the value to type `float`
<img width="300" alt="image" src="https://github.com/spirit-labs/tektite/assets/107602480/a061be77-abf2-46b6-9b9b-df9119c5ed73">

2. The example should have `parse_date` and not `format_date`
<img width="300" alt="image" src="https://github.com/spirit-labs/tektite/assets/107602480/a4d3df8e-1ac7-42b5-b116-87e176c53621">

3. maybe it is `hVal1`, `hVal2`, `hVal3`
```
kafka_build_headers(hName1: string, hVal1: A, hName1: string, hVal1: A, hName1: string, hVal1: A, ...)
```

4. I think we should return v where v>=0 or v<0
<img width="300" alt="image" src="https://github.com/spirit-labs/tektite/assets/107602480/74708a4c-8c22-4b90-afe8-b37bda5ac054">

5. The docs mention that `uint64_be` and `uint64_le` take only 1 argument. However, they take 2.

**Comment by purplefox** [comment]
> I think we should return v where v>=0 or v<0

No, I don't think that is right.

If v is < 0, e.g. -3, then we return -v, i.e. +3

**Comment by purplefox** [comment]
Other than the comments above, I have fixed the rest
