### ISSUE TITLE
Reduce number of key comparison in merge iterator

### ISSUE THREAD

**Issue by watson28** [spirit-labs/tektite#176]
The current approach of `merging_iter.go` in each call to `Next()` is to iterate over the list of iterators sequentially and find the next smallest key. This approach has a running time of `O(n*k)`, where
- k -> number of iterators
-  n -> number of the elements in each iter

Using a heap data structure, we can reduce the running time to `O(n*logK)`: https://en.wikipedia.org/wiki/K-way_merge_algorithm#Heap

To achieve this, the code must maintain the heap, an array of size `K`. If we store pointers to the `Current()` values of the iterator in the heap, this new approach should add a memory allocation of `8*K bytes`.  But with a significant improvement in the execution time of `merging_iter,` especially when K is big. Additionally, every time we make a key comparison between KV, we do extra operations, such as decoding the key and removing the version part. Less key comparisons will mean less of these two operations.

@purplefox Would Tektite be interested in this improvement? If so, I can work on it and share exact benchmark numbers after an initial implementation.

**Comment by purplefox** [comment]
I would say, by all means go ahead and investigate this, and if you can demonstrate a clear improvement in performance without too much GC overhead then it could make sense.
