### ISSUE TITLE
Has any schedule to implement SaslAuthenticate?

### ISSUE THREAD

**Issue by mikepop7** [spirit-labs/tektite#188]
Has any schedule to implement SASL Authenticate (PLAINTEXT)?  the API handler unsupported on current version.

**Comment by purplefox** [comment]
Hi @mikepop7 - there's an issue to implement Kafka auth here https://github.com/spirit-labs/tektite/issues/15
Currently we're working on generating Kafka protocol structs for all Kafka Apis - should be done in the next week or so.
Lots of other stuff to do too, so don't know when this will be done. If you want to give it a go, then any help is appreciated :)
