### ISSUE TITLE
Panic Error in Aggregation Function

### ISSUE THREAD

**Issue by ss-sakshi-kurhade** [spirit-labs/tektite#189]
We are using Kafka’s new writer ("[github.com/segmentio/kafka-go](http://github.com/segmentio/kafka-go)") in Golang  to store data in a stream and then perform an aggregate function on it. However, we are encountering the following error:
**Panic occurred in tektite not implemented for this agg func**

We have pulled the latest code just now but the issue persists. Below is the golang code - 

```go
package main

import (
    "context"
    "encoding/json"
    "fmt"
    "log"
    "math/rand"
    "time"

    "[github.com/segmentio/kafka-go](http://github.com/segmentio/kafka-go)"
)

type Data struct {
    VariableID  string  json:"variable_id"
    RandomValue float64 json:"random_value"
    Timestamp   int64   json:"timestamp"
}

func main() {
    writer := kafka.NewWriter(kafka.WriterConfig{
        Brokers:  []string{"[127.0.0.1:8880](http://127.0.0.1:8880/)"},
        Topic:    "my-topic",
        Balancer: &kafka.LeastBytes{},
    })

    defer writer.Close()

    for i := 0; i < 10; i++ {
        data := Data{
            VariableID:  GetVariableId(),
            RandomValue: rand.Float64() * 100,
            Timestamp:   time.Now().Unix(),
        }

        message, err := json.Marshal(data)
        if err != nil {
            log.Fatalf("Failed to marshal data: %v", err)
        }

        err = writer.WriteMessages(context.Background(),
            kafka.Message{
                Value: message,
            },
        )
        if err != nil {
            log.Fatalf("Failed to write messages: %v", err)
            continue
        }

        fmt.Printf("Produced message: %s\n", message)

        time.Sleep(5 * time.Second)
    }
}

func GetVariableId() string {
    variableId := map[int]string{0: "stu", 1: "abc", 2: "xyz", 3: "pqr", 4: "lmn"}
    randNum := rand.Intn(4)
    return variableId[randNum]
}
```

**Comment by purplefox** [comment]
Can you provide your stream definitions please?

**Comment by purplefox** [comment]
Looks like this is attempting to take the average of a string - average is only supported for numeric types: int, float, timestamp or decimal. Try using json_float instead of json_string, or you can explicitly convert using to_float/to_decimal etc.
Having said that, it shouldn't panic - that needs to be fixed.

**Comment by ss-sakshi-kurhade** [comment]
Thank You, the issue is now resolved but for reference, below is the complete stack trace of the error that we got 

tektite not implemented for this agg func
goroutine 76 [running]:
runtime/debug.Stack()
        /usr/lib/go-1.22/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/lib/go-1.22/src/runtime/debug/stack.go:16 +0x13
[github.com/spirit-labs/tektite/common.PanicHandler()](http://github.com/spirit-labs/tektite/common.PanicHandler%28%29)
        /home/sakshi/tektite/common/panic_handler.go:18 +0x5f
panic({0x170dac0?, 0x1b78b30?})
        /usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
[github.com/spirit-labs/tektite/opers.(*dummyAggFunc).ComputeString(..](http://github.com/spirit-labs/tektite/opers.%28*dummyAggFunc%29.ComputeString%28..).)
        /home/sakshi/tektite/opers/agg_funcs.go:469
[github.com/spirit-labs/tektite/opers.(*AggregateOperator).computeAggs(0xc0007abb08](http://github.com/spirit-labs/tektite/opers.%28*AggregateOperator%29.computeAggs%280xc0007abb08), 0xc000ec5280?, {0x1b9ba50, 0xc000ecee10})
        /home/sakshi/tektite/opers/aggregate.go:819 +0xc7f
[github.com/spirit-labs/tektite/opers.(*AggregateOperator).handleStreamBatch(0xc0007abb08](http://github.com/spirit-labs/tektite/opers.%28*AggregateOperator%29.handleStreamBatch%280xc0007abb08), 0xc000ec7170, {0x1b9ba50, 0xc000ecee10})
        /home/sakshi/tektite/opers/aggregate.go:407 +0xe7
[github.com/spirit-labs/tektite/opers.(*AggregateOperator).HandleStreamBatch(0xc0006b0f30](http://github.com/spirit-labs/tektite/opers.%28*AggregateOperator%29.HandleStreamBatch%280xc0006b0f30)?, 0x0?, {0x1b9ba50?, 0xc000ecee10?})
        /home/sakshi/tektite/opers/aggregate.go:395 +0x4e
[github.com/spirit-labs/tektite/opers.(*BaseOperator).sendBatchDownStream(0x1778fe0](http://github.com/spirit-labs/tektite/opers.%28*BaseOperator%29.sendBatchDownStream%280x1778fe0)?, 0xc000ec7170, {0x1b9ba50, 0xc000ecee10})
        /home/sakshi/tektite/opers/operators.go:191 +0xee
[github.com/spirit-labs/tektite/opers.(*partitionReceiver).ReceiveBatch(0xc00055bdc0](http://github.com/spirit-labs/tektite/opers.%28*partitionReceiver%29.ReceiveBatch%280xc00055bdc0), 0xc000ec7170, {0x1b9ba50, 0xc000ecee10})
        /home/sakshi/tektite/opers/partition.go:192 +0x333
[github.com/spirit-labs/tektite/opers.(*streamManager).HandleProcessBatch(0xc0006e2a00](http://github.com/spirit-labs/tektite/opers.%28*streamManager%29.HandleProcessBatch%280xc0006e2a00), {0x1b9ff60, 0xc00040b520}, 0xc000eccbd0, 0x5?)
        /home/sakshi/tektite/opers/mgr.go:1645 +0x3fc
[github.com/spirit-labs/tektite/proc.(*processor).processBatch(0xc00040b520](http://github.com/spirit-labs/tektite/proc.%28*processor%29.processBatch%280xc00040b520), 0xc000eccbd0, 0xee?)
        /home/sakshi/tektite/proc/processor.go:579 +0x3f
[github.com/spirit-labs/tektite/proc.(*processor).doHandleBatch(0xc00040b520](http://github.com/spirit-labs/tektite/proc.%28*processor%29.doHandleBatch%280xc00040b520), 0xc000eccbd0, 0x0, 0xc000ec5260)
        /home/sakshi/tektite/proc/processor.go:390 +0x7fb
[github.com/spirit-labs/tektite/proc.(*processor).ProcessBatch(0xc00040b520](http://github.com/spirit-labs/tektite/proc.%28*processor%29.ProcessBatch%280xc00040b520), 0xc000eccbd0, 0xc002312e10)
        /home/sakshi/tektite/proc/processor.go:330 +0x145
[github.com/spirit-labs/tektite/proc.(*processor).IngestBatch.func1()](http://github.com/spirit-labs/tektite/proc.%28*processor%29.IngestBatch.func1%28%29)
        /home/sakshi/tektite/proc/processor.go:301 +0x1f
[github.com/spirit-labs/tektite/proc.(*processor).loop(0xc00040b520)](http://github.com/spirit-labs/tektite/proc.%28*processor%29.loop%280xc00040b520%29)
        /home/sakshi/tektite/proc/processor.go:737 +0x1a6
[github.com/spirit-labs/tektite/proc.(*processor).runLoop(0xc00040b520](http://github.com/spirit-labs/tektite/proc.%28*processor%29.runLoop%280xc00040b520), 0xc000404d80)
        /home/sakshi/tektite/proc/processor.go:720 +0x89
[github.com/spirit-labs/tektite/proc.(*processor).SetLeader.func1()](http://github.com/spirit-labs/tektite/proc.%28*processor%29.SetLeader.func1%28%29)
        /home/sakshi/tektite/proc/processor.go:707 +0x1b
[github.com/spirit-labs/tektite/common.Go.func1()](http://github.com/spirit-labs/tektite/common.Go.func1%28%29)
        /home/sakshi/tektite/common/spawn.go:38 +0x93
created by [github.com/spirit-labs/tektite/common.Go](http://github.com/spirit-labs/tektite/common.Go) in goroutine 50
        /home/sakshi/tektite/common/spawn.go:31 +0x138

ref: @adpande

**Comment by purplefox** [comment]
I think what we need to do here is type check the aggregation function parameters at stream create time, which would disallow creating a stream like this.
