### ISSUE TITLE
Implement topic auto-create

### ISSUE THREAD

**Issue by purplefox** [spirit-labs/tektite#208]
The kafka property `create.topics.enable` when true causes topics to be created if they don't already exist when attempting to produce to them. We should support similar.

**Comment by akshat1998** [comment]
That will involve cluster level default configs. (at-least for partition count) 
Where can i find cluster config handling?

If we are going to support auto topic creation (and therefore with default partition count), should we also support [this](https://github.com/spirit-labs/tektite/blob/main/asl/kafka/spec/CreateTopicsRequest.json#L41), i.e. Allow manual topic creation with default partition count?
