### ISSUE TITLE
Allow multiple listeners for KafkaServer

### ISSUE THREAD

**Issue by purplefox** [spirit-labs/tektite#213]
Currently we only support one listener for Kafka-Server in our config.

Kafka supports multiple listeners which can be configured with different hosts/ports/authentication methods. 

We should allow a slice of Listeners to be specified in the config.

**Comment by rajatkb** [comment]
Picking this one up as discussed in Slack. 👀

**Comment by rajatkb** [comment]
@purplefox  Can you assign the issue to me ?
