### ISSUE TITLE
Create golang module for the Tektite client

### ISSUE THREAD

**Issue by purplefox** [spirit-labs/tektite#223]
The Tektite client currently lives in the asl/client directory. We should make it into a golang module with a go.mod file, and consider moving it somewhere else if appropriate.

**Comment by abhioncbr** [comment]
Can I give it a try?

**Comment by abhioncbr** [comment]
Do you think creating a new project, say `tektite-client` under spirit-labs org, makes sense for the separation?

**Comment by purplefox** [comment]
I think perhaps we should just keep the client in the same repo for now, but we can consider moving it out into a separate repo at a later date :)
