### ISSUE TITLE
Add support for Podman

### ISSUE THREAD

**Issue by vchandela** [spirit-labs/tektite#236]
- Currently, some tests are dependent on Docker and fail otherwise.
- We need some env var or flag to signal the tests that it's in Podman mode and have those tests succeed in such cases.
- This is a possible barrier to entry especially to contributors who are on Linux and have Podman.

Steps to complete this issue:
- Run `mage test`
- You'll find I believe 6 tests that fail due to expecting the Docker socket file
- Start figuring out a way to make that work, and start by making 1 test work with Podman
- Repeat.

**Comment by purplefox** [comment]
> We need some env var or flag to signal the tests that it's in Podman mode and have those tests succeed in such cases.

Instead of env var, perhaps you could try to connect to podman/docker, and if you get an error that you cannot connect try the other one?

**Comment by vchandela** [comment]
> > We need some env var or flag to signal the tests that it's in Podman mode and have those tests succeed in such cases.
> 
> Instead of env var, perhaps you could try to connect to podman/docker, and if you get an error that you cannot connect try the other one?

makes sense.
