### ISSUE TITLE
Use pointer to type in config to represent unset config setting

### ISSUE THREAD

**Issue by purplefox** [spirit-labs/tektite#36]
Currently in `conf.Config.ApplyDefaults()` we apply the defaults if the current value is the zero value of the type, e.g. zero or empty string. However this does not work well for config settings that can legitimately have the zero value as a configured value.

Instead we can refactor `Config` so that it maintains pointer to the type not the type itself, then if the value is nil it has not been set and we can apply defaults.

E.g. instead of:

```
type Config struct {
   ...
   MinioBucketName string
   MinioSecure     bool
    ...
}
```

Have:

```
type Config struct {
   ...
   MinioBucketName *string
   MinioSecure     *bool
    ...
}
```

**Comment by hxalid** [comment]
Hi @purplefox - thank you for open sourcing this project. It looks super interesting and I would like to contribute as well. I saw a discussion in another issue and you recommended new joiners to start with a "good first issue". If there is no objection me joining the project please assign this issue to me.

**Comment by purplefox** [comment]
Hey @hxalid welcome, and thanks for your interest!
Yes, you're more than welcome to take this task. Any questions pls start a discussion.
