### ISSUE TITLE
Script test for all functions

### ISSUE THREAD

**Issue by purplefox** [spirit-labs/tektite#45]
We should create a script test testing all available functions.

**Comment by vchandela** [comment]
@purplefox can I take up this issue? Please share necessary details.

**Comment by purplefox** [comment]
Hi @vchandela 

So basically, script tests are in the scripttest directory. The idea behind these tests is that they run a script of commands using the Tektite CLI and compare output with expected output. The actual tests are in the testdata directory - there are three files per test - the script file, the expected output file and a test data file for the test.
To run a test, run TestScriptStandalone or TestScriptThreeNodes in your IDE or on command line.
You can limit which script tests are run by specifying TestPrefixes in script_test_runner.go.
In this task what we're looking for is to test each of the in-built functions. https://tektitedb.com/functions/
Functions can be used in
* Projections
* Filters
* Sorts
I'd recommend getting things set-up and just getting one function working ok with a simple projection to begin with.

**Comment by vchandela** [comment]
@purplefox I've raised a PR for a `if()` working with a simple projection. Let me know if the changes look fine.
