### ISSUE TITLE
Consider simpler iterator abstraction

### ISSUE THREAD

**Issue by purplefox** [spirit-labs/tektite#82]
The current Iterator https://github.com/spirit-labs/tektite/blob/main/iteration/iter.go abstraction seems overcomplex leading to complex implementations.

We should consider simplifying it to something like:

```
type Iterator interface {
	Next() (bool, common.KV)
	Close()
}
```

Related to this. currently MergingIterator advances to next element if IsValid() is called twice in a row without Next()

**Comment by watson28** [comment]
@purplefox, I would like to take this one. Could you assign it to me?

**Comment by purplefox** [comment]
Happy to give this one to you if you want to give it a go. The tricky part will be in getting the MergingIterator to work with the new API.

**Comment by purplefox** [comment]
Hi @watson28 please see latest comments on the PR

**Comment by purplefox** [comment]
Issues fixed, so now closed
