### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by purplefox** [spirit-labs/tektite#92]
I've cleaned up this task so we can use it to track flaky tests which are currently skipped from the test suite, they are:

TestBridgeSimulateNetworkFailure
TestBridgeKafkaInitiallyUnavailable
TestFailoverReplicationQueuesWithAggregation
TestFailoverReplicationQueuesWithAggregationFailLevelManagerNode

They should be fixed as soon as possible, but we have a policy of skipping flaky tests immediately so we can maintain a green test run for developers, otherwise it's hard for them to reason about the results of CI on their PRs.

**Comment by devguyio** [comment]
So far running tests with #93 , the score is 1/3 successful runs. 
1. Failed (timedout , lost the log)
2. Passed
3. Failed. Logs [test-results.log](https://github.com/user-attachments/files/15545732/test-results.log)

**Comment by naveen246** [comment]
@purplefox @devguyio 
Is anyone working on this ?
